#해당 파일에 기입될 정보중 secret에 해당되는 정보가 있으므로 gitignore에 config.toml을 추가한다
#git repository에 올라가지 않도록 한다
52genie_token = "Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY4ODk2MDE5OCwianRpIjoiZTBhNzkyYWEtN2EwNC00ZDJiLTkyNjMtMDk2MmEzNTMzNGRhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6ImFwcHNtaXRoIiwibmJmIjoxNjg4OTYwMTk4LCJzY29wZSI6IkFETUlOIn0.MncQ5BGfCAo5W0h-pYiD7bNtgphk0bQWNi_KRLDPoo0"

